GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiV2lsbGlhbSIsImlhdCI6MTY1MzMzNTA5MiwiZXhwIjoxNjUzMzM1MTA3fQ.DibsuiCVKmsmsfVl4_h-IwW2eQLfSaTNol4NliuIB2A

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiV2lsbGlhbSIsImlhdCI6MTY1MzMzNjMxNn0.-0MeiYdK8k04rLo_dBjHeYgey1FD9qEIfsNHc4_RzYQ"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiV2lsbGlhbSIsImlhdCI6MTY1MzMzNjMxNn0.-0MeiYdK8k04rLo_dBjHeYgey1FD9qEIfsNHc4_RzYQ"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "William"
}